### ISSUE TITLE
Process description should state that back-end can derive

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo.org#27]
Originates from https://github.com/Open-EO/openeo-processes/pull/215#discussion_r551218809

processes.openeo.org and all other places where the general processes are shown to users should state that these are just the generic specifications and back-ends can derive from that. We should guide users how they can find/request the back-end specific process descriptions in the clients.

**Comment by soxofaan** [comment]
Related idea (probably for another github ticket): on hub.openeo.org and editor.openeo.org: add visual indication that a process provided by a backend differs from official spec

**Comment by m-mohr** [comment]
Yes, indeed: https://github.com/Open-EO/openeo-web-editor/issues/32

**Comment by m-mohr** [comment]
> **Note:** This is the list of all processes specified by the openEO project. Back-ends implement a varying set of processes. Thus, the processes you can use at a specific back-end may derive from the specification, may include non-standardized processes and are likely not implement all processes listed here. Please check each back-end individually for the processes they support.

**Comment by m-mohr** [comment]
![image](https://user-images.githubusercontent.com/8262166/114430257-8c028900-9bbe-11eb-8465-f5745ad81c26.png)

**Comment by m-mohr** [comment]
This is available at openeo.org (see https://openeo.org/documentation/1.0/processes.html ) now and will be available to processes.openeo.org (draft & 1.0.0) once the CDN has updated.

**Comment by soxofaan** [comment]
I think there is a typo in there:

> Thus, the processes you can use at a specific back-end may ... and **are likely not implement** all processes

**Comment by m-mohr** [comment]
Argh, going to fix it in all places... Thanks.
