### ISSUE TITLE
Cookbook: Show h4 headers in TOC

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo.org#49]
Originates from #47: Right now only h1, h2 and h3 headers are shown in the TOC of the cookbook. It would be great to show also h4 headers in the TOC.

In theory, it should work to add this to the markdown file as frontmatter:
```
---
sidebarDepth: 3
---
```

and also add the following to the config:
```
    markdown: {
      extractHeaders: [ 'h2', 'h3', 'h4' ]
    }
```

It does not work for me, maybe we have an outdated version and need to upgrade VuePress? Or something else is not working...

See also: https://github.com/vuejs/vuepress/issues/1715

**Comment by jonathom** [comment]
There is really no way to include multiple h1 headers, right?

**Comment by m-mohr** [comment]
I don't think so, it's also not semantically correct. There should be only one h1 per document.

**Comment by m-mohr** [comment]
This works now!

**Comment by bihell** [comment]
It works!
