### ISSUE TITLE
HTTPS is not set up correctly

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo.org#5]
When opening https://openeo.org Firefox tells me that "This connection is not secure".

> openeo.org uses an invalid security certificate.
The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by edzer** [comment]
The github settings page reports:
```
Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS (openeo.org) — Troubleshooting custom domains 
HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
When HTTPS is enforced, your site will only be served over HTTPS. Learn more.
```
with this link: https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by m-mohr** [comment]
I sent a request to the Webteam and I hope they can solve it by updating the IP addresses.

**Comment by m-mohr** [comment]
Should be available in the next 24 hours.

**Comment by m-mohr** [comment]
HTTPS is available now.
