### ISSUE TITLE
Cookbook: PNG options are from GEE

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo.org#54]
In the Cookbook there's an example that is very GEE specific as it lists three options from GEE:
https://openeo.org/documentation/1.0/cookbook/#raster-formats-png

We should document better (with a warning box?) that users need to check back-end options on how to set PNG RGB layers to bands and that the example given is specific to GEE.

**Comment by clausmichele** [comment]
I've actually implemented this at Eurac following the same structure you have for GEE.
How do we streamline this? Should we agree on the properties to use if the back-end offers this functionality?

**Comment by m-mohr** [comment]
Good question. I have no answer yet. I assume we could open a document with recommendations in openeo-processes or openeo-api. Other than that we only have the Platform-specific agreement https://docs.openeo.cloud/federation/#file-formats right now.

**Comment by m-mohr** [comment]
@clausmichele No, save_result is file-format agnostic. These tings should be defined in /file_formats. To align, we could instead write a best practice for specific file-formats, like we have started for Platform already: https://docs.openeo.cloud/federation/backends/fileformats.html I guess we should add PNG and JPEG there and could then evolve from Platform to general openEO at some point.

**Comment by clausmichele** [comment]
Alright. I will implement the PNG format for EODC so that both back-ends in the aggregator have it and later we will be able to improve that document adding PNG details.
