### ISSUE TITLE
Data cube guide is wrong about aggregate_spatial

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo.org#55]
The data cube guide talks about aggregate_spatial in a way that it can take 4D cubes and work on them, but the specification of aggregate_spatial only allows to work on 3D cubes:

> The data cube must have been reduced to only contain two spatial dimensions and a third dimension the values are aggregated for, for example the temporal dimension to get a time series. Otherwise, this process fails with the TooManyDimensions exception.

We should probably remove the mention of aggregate_spatial and keep the description general. aggregate_spatial can then be mentioned as a variant that works on 3D only.

**Comment by soxofaan** [comment]
FYI: the VITO backend supports `aggregate_spatial` on 4D cubes (t, band, x, y), which is actually a feature we commonly use in demo's.
