### ISSUE TITLE
hidden title for "fragment" links

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo.org#66]
From several places we have "fragment" links to openeo.org pages, 
e.g. https://openeo.org/documentation/1.0/glossary.html#eo-data-collections
When you visit such a link directly, the title of that section ("EO data (Collections)")  is unfortunately hidden behind the header at the top:
![Screenshot from 2022-06-03 22-12-40](https://user-images.githubusercontent.com/44946/171944394-76eee3b6-351b-4337-bf47-54d34c25ed3b.png)

**Comment by soxofaan** [comment]
There are plenty of (CSS/JS) solutions to be found online, but I'm not sure what is recommended/ or best practice nowadays

**Comment by m-mohr** [comment]
Tried to fix this with various CSS "solutions", but I couldn't make it work. I assume some vuepress JS interferes with it.
We are using a custom template, which includes a lot of changes compared to the latest version and as auch I can't really figure out what makes it work there or what is missing/broken. 
As this is not a big issue I don't expect a fix unless we take some days and update the template to the latest version.

**Comment by m-mohr** [comment]
Just after writing this I had another idea and now it works :-)

**Comment by soxofaan** [comment]
confirmed (Firefox and Chromium on Linux)
thanks!
