### ISSUE TITLE
Update "Getting started with openEO and Open Data Cube"

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo.org#74]
It's outdated and needs to be updated to the new libraries such as openeo-processes-dask etc.
Maybe point to client-side processing, too.
Explain relation to Pangeo?

cc @clausmichele

**Comment by clausmichele** [comment]
Thanks for founding this Matthias. It would be good to collaborate with EODC for this, the page was written by me and Sophie when she was at EODC.
@LukeWeidenwalker @ValentinaHutter @SerRichard

**Comment by ValentinaHutter** [comment]
Thanks for pointing this out! I now created a first PR to update the references to the openeo-processes-dask and openeo-pg-parser-networkx. https://github.com/Open-EO/openeo.org/pull/76/files and a review would be appreciated. It would be great, if you could add the client side processing part. Let me know, if we need further coordination for this. :)

**Comment by clausmichele** [comment]
Currently ODC is not used at all in `openeo-processes-dask` tough. I do see different options:
1. We implement the `load_collection` process as an extra submodule of `openeo-processes-dask` (probably we can just reuse the one from `openeo-odc`)
2. We drop ODC and we just mention Xarray in this doc
3. Last option, we keep ODC and we show how to implement a sample `load_collection` process, but we don't include it in the repo. In this way, we could also add other `load_collection` examples (like the one from client side processing for local data) and also another one using a STAC catalog.

**Comment by ValentinaHutter** [comment]
Thank you for the quick reply, I now updated my draft following your idea 3. and added a section about load collection with ODC and STAC. Would be great if you could add a section about client side processing. Let me know, if I should update any other section.

**Comment by m-mohr** [comment]
Closed by #76
