### ISSUE TITLE
use of earth engine backend in 'getting started samples'?

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo.org#81]
Via openEO platform support, we received a message from a somewhat frustrated user who followed our Python 'getting started' example.
It directed him to the earth engine backend, and then mentioned 'OIDC authentication' which of course doesn't work: 
https://openeo.org/documentation/1.0/python/#installation

So to fix this, there's various options:

1. Put a warning in place that more clearly explains the state of the GEE backend
2. Use a different backend

**Comment by m-mohr** [comment]
There is a mention that only Basic is supported.So it seems the user didn't fully read the guide. We can of course make the warning larger, but as usual people will also not always read that. 

> For Google Earth Engine, only [Basic Authentication](https://openeo.org/documentation/1.0/python/#basic-authentication) is supported at the moment.
