### ISSUE TITLE
Add License note to docs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo.org#87]
It's not easy to find the license of the openeo.org docs at https://openeo.org/documentation/1.0/ 

Each page has a footer with "edit this page" and "Last updated". Is it easy to add license info there too?

**Comment by soxofaan** [comment]
related to https://github.com/eu-cdse/documentation/issues/520

**Comment by m-mohr** [comment]
@soxofaan You could probably add it here: https://github.com/Open-EO/openeo.org/blob/master/.vuepress/theme/components/PageEdit.vue
