### ISSUE TITLE
Link to API reference is super hidden

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo.org#95]
It is super hard to find the link to the [actual API reference](https://openeo.org/documentation/1.0/developers/api/reference.html) on the website. IMO it should be a direct entry in the "User Documentation" section of the menu. But at least it should be somewhat prominently linked on https://openeo.org/documentation/1.0/ -- the current location of the link under the "Contribute" heading is not suitable.

**Comment by m-mohr** [comment]
It's intentional, the API is in the developer documentation as end-users shouldn't need the API due to the client software. The API is not meant for scientists etc.
